#  _______ ___     _______ ___ ___ _______ _______     _______ ______   
# |   _   |   |   |   _   |   Y   |   _   |   _   \   |   _   |   _  \
# |.  1   |.  |   |.  1   |   1   |.  1___|.  l   /   |.  1   |.  |   \
# |.  ____|.  |___|.  _   |\_   _/|.  __)_|.  _   1   |.  _   |.  |    \
# |:  |   |:  1   |:  |   | |:  | |:  1   |:  |   |   |:  |   |:  1    /
# |::.|   |::.. . |::.|:. | |::.| |::.. . |::.|:. |   |::.|:. |::.. . /
# `---'   `-------`--- ---' `---' `-------`--- ---'   `--- ---`------'
#
# PROGRAMMER: EUKALYPTENHD
# VERSION: 1.0
# DON'T FORGET TO LEAVE A REVIEW WITH SUGGESTIONS ON WHAT TO ADD NEXT!
#



# ADVERTISE MESSAGE SETTINGS
# THIS CAN BE AS LONG AS YOU LIKE :D
advertisemessage:
    - ''
    - '&8&m+&6&m-------------------------&8&m+&6&m'
    - ''
    - '&b&lAnunt'
    - ''
    - '&b%player% &8>> &3%message%'
    - ''
    - '&8&m+&6&m-------------------------&8&m+&6&m'
    - ''
advertisemessagesound: 'FIREWORK_LAUNCH'



# COOLDOWN MESSAGE SETTINGS
cooldownmessage: '&bJump Romania &8>> &3Trebuie sa mai astepti %seconds% de secunde pana sa dai iar un anunt!'
cooldownsound: 'FIREWORK_LAUNCH'

# THIS IS IN SECONDS!
advertisecooldown: 120



# SYNTAX MESSAGE SETTINGS
syntaxmessage: '&bSYNTAX &8>> &b/advertise <message>'
syntaxsound: 'FIREWORK_LAUNCH'



# NO PERMISSION MESSAGE SETTINGS
nopermissionmessage: '&bPERMISSION &8>> &3You have no authority to do this.'
nopermissionsound: 'FIREWORK_LAUNCH'



# CONSOLE NOT ALLOWED MESSAGE SETTINGS
consolenotallowedmessage: '&bPERMISSION &8>> &3You cannot advertise through the console.'